trigger: none

variables:
  CDP_DEFINITION_BUILD_COUNT: $[counter('', 0)]
  DEBIAN_FRONTEND: noninteractive

resources:
  repositories: 
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

extends:
  template: v2/OneBranch.Official.CrossPlat.yml@templates
  parameters:
    git:
      submodules: false
    globalSdl: # https://aka.ms/obpipelines/sdl
      # tsa:
      #  enabled: true
      # credscan:
      #   suppressionsFile: $(Build.SourcesDirectory)\.config\CredScanSuppressions.json
      prefast:
        enabled: false
      cg:
        failOnAlert: false
      policheck:
        break: true # always break the build on policheck issues. You can disable it by setting to 'false'
        exclusionsFile: '$(Build.SourcesDirectory)\tools\ci_build\policheck_exclusions.xml'
      # suppression:
      #   suppressionFile: $(Build.SourcesDirectory)\.gdn\global.gdnsuppress

    stages:
    - stage: Windows_Build
      jobs:
      - template: .pipelines/windowsai-steps.yml@self
        parameters:
          BuildArch: x64
          
      - template: .pipelines/windowsai-steps.yml@self
        parameters:
          BuildArch: x86
          PythonPackageName: pythonx86
          
      - template: .pipelines/windowsai-steps.yml@self
        parameters:
          BuildArch: arm
          
      - template: .pipelines/windowsai-steps.yml@self
        parameters:
          BuildArch: arm64
          
      - template: .pipelines/windowsai-steps.yml@self
        parameters:
          BuildArch: x64
          Runtime: static
          
      - template: .pipelines/windowsai-steps.yml@self
        parameters:
          BuildArch: x86
          PythonPackageName: pythonx86
          Runtime: static
          
      - template: .pipelines/windowsai-steps.yml@self
        parameters:
          BuildArch: arm
          Runtime: static
          
      - template: .pipelines/windowsai-steps.yml@self
        parameters:
          BuildArch: arm64
          Runtime: static